server:
  port: 8761
spring:
  application:
    name: ServiceRegistry

eureka:
  client:
    # We are the server, we don't need to register ourselves with another server.
    register-with-eureka: false
    # We don't need to fetch a registry copy from ourselves.
    fetch-registry: false
  instance:
    hostname: localhost